config/routes.rb
Practiceforum::Application.routes.draw do
  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  root :to => "forums#index" 

  resources :forums do
    resources :posts do
      post :plus, :on => :member
    end
  end
  namespace "admin" do
    resources :forums do
      resources :posts
    end
    root :controller => "forums", :action => "index"
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                :integer(4)      not null, primary key
#  title             :string(255)
#  content           :text
#  forum_id          :integer(4)
#  created_at        :datetime
#  updated_at        :datetime
#  user_id           :integer(4)
#  file_file_name    :string(255)
#  file_content_type :string(255)
#  file_file_size    :integer(4)
#  file_updated_at   :datetime
#

class Post < ActiveRecord::Base
  belongs_to :forum, :counter_cache => true
  belongs_to :user

  has_attached_file :file

  validates :title, :presence   => true
  validates :content, :presence   => true
  validates :forum_id, :presence   => true
  #validates :user_id, :presence   => true

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  include AuthenticatedSystem
  before_filter :require_is_admin
  before_filter :find_post, :only => [ :show, :edit, :update, :destroy ]

  def index
    @forum = Forum.find(params[:forum_id])
    @posts = @forum.posts.paginate(:page => params[:page], :per_page => 20, :order => 'id DESC')
  end
  def show
  end
  def edit
  end
  def update
    @post.update_attributes(params[:post])
    
    redirect_to admin_forum_post_path(@post.forum_id, @post)
  end
  def destroy
    @post.destroy
    
    redirect_to admin_forum_path(params[:forum_id])
  end

  protected

  def find_post
    @forum = Forum.find(params[:forum_id])
    @post = @forum.posts.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include AuthenticatedSystem
  before_filter :login_required, :except => [:show, :index, :plus]
  before_filter :find_forum
  before_filter :find_post, :except => [:index, :new, :create]

  def index
    @posts = @forum.posts.paginate(:page => params[:page], :per_page => 20, :order => 'id DESC')
  end

  def show
  end
  def new
    @post = @forum.posts.new
  end
  def create
    @post = @forum.posts.new(params[:post])
    @post.user_id = current_user.id
    @post.save

    redirect_to forum_post_path(@forum, @post)
  end
  def edit
    @post = current_user.posts.find(params[:id])
  end
  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to forum_post_path(@post.forum_id, @post)
    else
      render :edit
    end
  end
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    
    redirect_to forum_posts_path(params[:forum_id])
  end
  def plus
    @post.score = @post.score + 1
    @post.save

    respond_to do |format|
      format.any { render :json => {
        :forum_id => @post.forum_id,
        :post_id => @post.id,
        :score => @post.score
      } }
    end
  end

  protected
  def find_forum
    @forum = Forum.find(params[:forum_id])
  end
  def find_post
    @post = @forum.posts.find(params[:id])
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
  def admin_edit_delete_link(post)
    out = ""
    out << "<p>"
    out << link_to('edit post', edit_admin_forum_post_path(post.forum_id, post))
    out << ","
    out << link_to('delete post', admin_forum_post_path(post.forum_id, post), :method => :delete)
    out << "</p>"
    out.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def edit_delete_link(post)
    out = ""
    if current_user.id == post.user_id
      out << "<p>"
      out << link_to('edit post', edit_forum_post_path(post.forum_id, post))
      out << ","
      out << link_to('delete post', forum_post_path(post.forum_id, post), :method => :delete)
      out << "</p>"
    end
    out.html_safe
  end
end

app/views/posts/edit.html.erb
<%= form_for @post, :url => forum_post_path(@post.forum_id, @post), :html => { :method => :put } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Update" %>
<% end %>

app/views/posts/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "forum.js" %>
<% end %>

<h1><%= @forum.name %></h1>
<ol>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, forum_post_path(@forum, post) %>
      [<span id="<%= "forum#{@forum.id}-post#{post.id}-score" %>"><%= post.score %></span>]
      [<%= link_to "+1", plus_forum_post_path(@forum, post), :remote => true, :method => :post, "data-type" => :json %>]
    </li>
  <% end %>
</ol>

<%= will_paginate @posts %>
<p><%= link_to "New Post", new_forum_post_path %></p>
<p><%= link_to "Index", root_path %></p>

app/views/posts/new.html.erb
<%= form_for @post, :url => forum_posts_path, :html => {:multipart => true} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.file_field :file %>
  <%= f.submit "Create" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<% if @post.file %>
<p>
  <%= link_to @post.file.url %>
</p>
<% end %>
<p>
  <%= link_to 'edit post', edit_forum_post_path(@post.forum_id, @post) %>,
  <%= link_to 'delete post', forum_post_path(@post.forum_id, @post), :method => :delete %>
</p>
<p><%= link_to 'back to forum', forum_path(@forum) %></p>