config/routes.rb
Practiceforum::Application.routes.draw do
  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  root :to => "forums#index" 

  resources :forums do
    resources :posts do
      post :plus, :on => :member
    end
  end
  namespace "admin" do
    resources :forums do
      resources :posts
    end
    root :controller => "forums", :action => "index"
  end
end

app/models/forum.rb
# == Schema Information
#
# Table name: forums
#
#  id          :integer(4)      not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  posts_count :integer(4)      default(0)
#

class Forum < ActiveRecord::Base
  has_many :posts, :autosave => true, :dependent => :destroy

  validates :name, :presence   => true
end

app/controllers/admin/forums_controller.rb
class Admin::ForumsController < Admin::BaseController
  include AuthenticatedSystem
  before_filter :require_is_admin

  def index
    @forums = Forum.all
  end
  def show
    @forum = Forum.find(params[:id])
    redirect_to admin_forum_posts_path(@forum)
  end
  def new
    @forum = Forum.new
  end
  def create
    @forum = Forum.new(params[:forum])
    if @forum.save
      redirect_to admin_forum_posts_path(@forum)
    else
      render :new
    end
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  include AuthenticatedSystem
  before_filter :find_forum, :only => [:show]

  def index
    @forums = Forum.all
  end
  def show
    redirect_to forum_posts_path(@forum)
    #@posts = @forum.posts.paginate(:page => params[:page], :per_page => 20, :order => 'id DESC')
  end
   
  protected

  def find_forum
    @forum = Forum.find(params[:id])
  end
end

app/helpers/admin/forums_helper.rb
module Admin::ForumsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/admin/forums/index.html.erb
<h1>Forum Index</h1>

<ol>
  <% @forums.each do |forum| %>
    <li><%= link_to forum.name, admin_forum_path(forum) %>, <%= forum.posts.size %></li>
  <% end %>
</ol>

<%= link_to "new forum", new_admin_forum_path %>

app/views/admin/forums/new.html.erb
<h2>New Forum:</h2>

<%= form_for @forum, :url => admin_forums_path do |f| %>
  <%= f.label :name, "Title" %> <br/>
  <%= f.text_field :name %> <br/>

  <%= f.label :description, "Description" %> <br/>
  <%= f.text_field :description %> <br/>
  
  <%= f.submit "Create" %>
<% end %>

app/views/admin/forums/show.html.erb
<h1><%= @forum.name %></h1>
<%= link_to 'New Post', new_admin_forum_post_path(@forum) %>
<ol>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, admin_forum_post_path(@forum, post) %></li>
  <% end %>
</ol>

<%= will_paginate @posts %>